platform :ios, '10.0'
use_frameworks!

target 'DataFramework_Example' do
  pod 'DataFramework', :path => '../'

  target 'DataFramework_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0'
    pod 'Nimble', '~> 7.0'
  end
end
